package by.epam.webauction.controller.command;

public enum CommandName {
    SIGN_IN, SIGN_UP, SIGN_OUT, INIT_DATA, DESTROY_DATA, CHANGE_LOCALIZATION, ADD_LOT, DEL_LOT, ADD_AUC, DEL_AUC, AUCTIONS_UPDATE, AUCTIONS_UPDATE_FOR__DELETE_LOTS, REFRESH_AUCTION, PLACE_BET, SELL_LOT, NO_SUCH_COMMAND
}
